version: "3.2"
services:
  news-postgres:
    image: postgres:14.1
    container_name: 'news-postgres'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - $PWD/postgres/news/init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
      - $PWD/postgres/news/migrations:/var/lib/migrations
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      sf-net:

  comments-postgres:
    image: postgres:14.1
    container_name: 'comments-postgres'
    restart: always
    ports:
      - '5433:5432'
    volumes:
      - $PWD/postgres/comments/init.sh:/docker-entrypoint-initdb.d/postgres-init.sh
      - $PWD/postgres/comments/migrations:/var/lib/migrations
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      sf-net:

networks:
  sf-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.1.0.0/24
